export const actionTypes = {
  CLEAR_CURRENT_ARTICLE: 'blog/CLEAR_CURRENT_ARTICLE',
  /* ------------------------ */
  GET_ARTICLE_SUCCESS: 'blog/GET_ARTICLE_SUCCESS',
  GET_ARTICLE_FAILED: 'blog/GET_ARTICLE_FAILED',
  /* ------------------------ */
  LOAD_ARTICLES_SUCCESS: 'blog/LOAD_ARTICLES_SUCCESS',
  LOAD_ARTICLES_FAILED: 'blog/LOAD_ARTICLES_FAILED',
  /* ------------------------ */
  LOAD_RELATED_SUCCESS: 'blog/LOAD_RELATED_ARTICLES_SUCCESS',
  LOAD_RELATED_FAILED: 'blog/LOAD_RELATED_ARTICLES_FAILED',
  /* ------------------------ */
  LOAD_NEARBY_SUCCESS: 'blog/LOAD_NEARBY_ARTICLES_SUCCESS',
  LOAD_NEARBY_FAILED: 'blog/LOAD_NEARBY_ARTICLES_FAILED',
  /* ------------------------ */
  CLEAR_FOUND_ARTICLES: 'blog/CLEAR_FOUND_ARTICLES',
  /* ------------------------ */
  FIND_ARTICLES_PENDING: 'blog/FIND_ARTICLES_PENDING',
  FIND_ARTICLES_SUCCESS: 'blog/FIND_ARTICLES_SUCCESS',
  FIND_ARTICLES_FAILED: 'blog/FIND_ARTICLES_FAILED',
};
