import React from 'react';
import { priority, tagsForBlog } from 'utils/constants';

export const arrows = {
  prev:
  <svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" viewBox="0 0 10 16">
    <path fill="none" fillRule="evenodd" stroke="#AFC0CE" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 1L1 8l8 7" />
  </svg>,
  next:
  <svg xmlns="http://www.w3.org/2000/svg" width="10" height="16" viewBox="0 0 10 16">
    <path fill="none" fillRule="evenodd" stroke="#AFC0CE" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 1l8 7-8 7" />
  </svg>,
};

export const articlesData = [
  {
    id: 0,
    title: 'How We Developed Fireaway, the Simplest Chat in the World',
    published_at: '2019-10-30T08:06:58.000Z',
    description: 'While the world of chat apps continually becomes more complicated, we opt for simplicity. Meet our new product – Fireaway, the simplest chat in the world. It is a single-use anonymous chat, where you don’t need to register – just open the browser tab, invite a friend with the link, and start chatting!',
    slug: 'how-we-developed-fireaway-the-simplest-chat-in-the-world',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/068/original/Fireaway_header_preview_.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 1,
    title: 'Load Testing',
    published_at: '2019-01-21T20:23:45.000Z',
    description: 'Let’s figure out why you should never neglect load testing in your projects and when it’s the best time to embark on it. ',
    slug: 'load-testing',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/024/original/4.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 2,
    title: '7 Benefits Of Using Chatbots For Your Business',
    published_at: '2019-02-13T20:32:53.000Z',
    description: '7 reasons why chatbots are so cool (and save your time, money and so much more!)',
    slug: '7-benefits-of-using-chatbots-for-your-business',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/025/original/12.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 3,
    title: 'Software Product Design: What Do the Best Apps Have in Common?',
    published_at: '2019-02-27T20:29:10.000Z',
    description: 'Find out how to create a web and mobile design that will make the experience of interacting with your product pleasant and effective. ',
    slug: 'software-product-design-what-do-the-best-apps-have-in-common',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/026/original/3.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 4,
    title: '10 Best Chatbot Examples to Improve Customer Service in 2019',
    published_at: '2019-03-12T14:02:22.000Z',
    description: 'Do you want to find the best chatbots online and see how many different things that they can do? We already did it! Join us to share our passion for chatbots and tech in our latest article:)',
    slug: '10-best-chatbot-examples-to-improve-customer-service-in-2019',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/027/original/10.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 5,
    title: 'How To Make A Chatbot From Scratch',
    published_at: '2019-03-19T12:17:35.000Z',
    description: 'Want to build a chatbot from scratch? Check out our step-by-step chatbot development guide based on one of our projects (a cool GIF included : )',
    slug: 'how-to-build-a-chatbot-from-scratch',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/028/original/11.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 6,
    title: 'Yellow Recognized as an Industry Leader',
    published_at: '2019-03-26T13:19:54.000Z',
    description: "We're proud to be 8th from more than 100 app developers in Belarus! Hooray!:)",
    slug: 'yellow-recognized-as-an-industry-leader',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/029/original/5.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 7,
    title: 'How to Send a Cat via a Chat or Chat Architecture in a Nutshell',
    published_at: '2019-04-02T12:47:24.000Z',
    description: 'Let’s explore the darkest corners of the insides of chat to help a GIF of a funny cat find its way from your phone to your friend’s phone',
    slug: 'how-to-send-a-cat-via-a-chat-or-chat-architecture-in-a-nutshell',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/034/original/9.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 8,
    title: 'How We Created Famlicious, a Family Chat App for iOS and Android',
    published_at: '2019-04-09T19:37:06.000Z',
    description: 'Find out how we built a family chat app that connects users with their families, facilitates family communications, and provides a unique way of building family trees.',
    slug: 'how-we-created-famlicious-a-family-chat-app-for-ios-and-android',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/035/original/13.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 9,
    title: 'Selenium–Why We Love It So Much (part 1)',
    published_at: '2019-04-16T16:42:32.000Z',
    description: 'Selenium is truly amazing, and there’s a video in this article proving that. Join us to learn about how you can save time and money (and make your testers happier!) on your next project.',
    slug: 'selenium-why-we-love-it-so-much-part-1',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/038/original/1.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 10,
    title: 'How to Make a Social Media App from Scratch?',
    published_at: '2019-04-23T16:42:35.000Z',
    description: 'How do you build a great social network application from scratch? Explore the social media app development stages, trends, and features.',
    slug: 'how-do-you-make-a-social-media-app-from-scratch',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/039/original/building_header.png.jpeg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 11,
    title: 'Complete Guide to the Chat Architecture',
    published_at: '2019-04-30T16:44:24.000Z',
    description: 'After years of work we developed our own version of chat architecture and its components which helps us to create well-structured and successful chats. Join us to see how we do it!',
    slug: 'guide-to-the-chat-architecture',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/041/original/chat.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 12,
    title: 'Four Amazing Things We Did At Collision In New Orleans',
    published_at: '2018-07-17T18:27:30.000Z',
    description: 'On this rainy Tuesday, we flash back to the sunny spring days and recall the happiest moments at the Collision conference in New Orleans. Join in!',
    slug: 'four-amazing-things-we-did-at-collision-in-new-orleans',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/008/original/Collision_main-%281%29.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 13,
    title: 'StickerBox–Episode 1: Why We Failed When We Tried to Segment Faces With Algorithms',
    published_at: '2018-08-08T15:14:42.000Z',
    description: 'With this article, we are launching a series of stories casting light on the ups and downs behind StickerBox. Spoiler: with all the downs, we made it! ',
    slug: 'stickerbox-episode-1-why-we-failed-when-we-tried-to-segment-faces-with-algorithms',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/010/original/stickerbox_main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 14,
    title: 'How To Be A Good Customer',
    published_at: '2018-08-13T18:49:43.000Z',
    description: 'Based on real cases: check out our tips on how to stay focused, confident, and cooperative when working with your engineering team',
    slug: 'how-to-be-a-good-customer',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/014/original/15.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 15,
    title: 'Why You Should Use Kubernetes In Your Next Project',
    published_at: '2018-08-30T12:50:33.000Z',
    description: 'Seriously, what is so special about container orchestration tools? Let’s unpack Kubernetes and see what it has in store.',
    slug: 'why-you-should-use-kubernetes-in-your-next-project',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/015/original/main_F_%281%29.png',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 16,
    title: 'Do You Guys Ever Sleep??? Or How To Manage Time Difference',
    published_at: '2018-09-07T15:14:42.000Z',
    description: 'In this article, we share three simple rules how to make time difference management as easy as 1-2-3. Take a look! ',
    slug: 'do-you-guys-ever-sleep-or-how-to-manage-time-difference',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/016/original/16.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 17,
    title: 'What are the Benefits of DevOps for your Business?',
    published_at: '2018-09-25T11:12:55.000Z',
    description: 'So, why is everyone talking about DevOps, and what it has to offer? Let’s figure it out now!',
    slug: 'what-is-devops-and-does-your-team-need-it',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/017/original/14.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 18,
    title: 'Monolithic Architecture vs. Microservices: Choosing the Right Architecture for the Project ',
    published_at: '2018-10-15T13:26:16.000Z',
    description: 'There are two ways of building complex systems—either using monolithic or microservices architecture. Which one to choose and when? Let’s figure it out!',
    slug: 'monolithic-architecture-vs-microservices-choosing-the-right-architecture-for-the-project',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/018/original/main-2.png',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 19,
    title: 'QA Automation: How It Can Help Your Product',
    published_at: '2018-10-23T16:42:45.000Z',
    description: 'Answers to all embarrassing questions about automated testing that you always wanted to ask but were afraid to. Help yourself!',
    slug: 'qa-automation-how-it-can-help-your-product',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/019/original/1.main-2.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 20,
    title: '#WebSummit2018',
    published_at: '2018-11-09T13:01:26.000Z',
    description: 'Want to know what the three days at the Web Summit in Lisbon felt like? Spoiler: it was legen-wait-for-it… dary!',
    slug: 'websummit2018',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/020/original/main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 21,
    title: 'REST Security Basics',
    published_at: '2018-12-03T13:04:13.000Z',
    description: 'From basic authentication to JSON web tokens—four ways to implement user authorization in a nutshell.',
    slug: 'rest-security-basics',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/021/original/6.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 22,
    title: 'Six Reasons To Fall In Love With React',
    published_at: '2018-12-17T11:29:34.000Z',
    description: 'From a huge shared codebase to well-defined data flow—see our personal list of six valid reasons to fall for React if you haven’t already done so',
    slug: 'six-reasons-to-fall-in-love-with-react',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/022/original/7.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 23,
    title: 'Selenium–Why We Love It So Much (part 2)',
    published_at: '2019-05-08T07:56:24.000Z',
    description: 'Here are the top 10 reasons why Selenium is the best tool for testing web applications on the market (and 3 reasons that make it less perfect–but who cares when it’s so cool anyway? : ) )',
    slug: 'selenium-why-we-love-it-so-much-part-2',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/042/original/2-2.jpg',
    priority: priority.high,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 24,
    title: 'How to Create a Location-Based App? ',
    published_at: '2019-05-14T20:15:16.000Z',
    description: 'Dropbox, banking and coupon apps, and even your planner–what do all of these apps have in common? Find the answer in the article!',
    slug: 'how-to-create-a-location-based-app',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/043/original/Location_header_1160x670.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 25,
    title: 'How to Build a Scalable Web Application?',
    published_at: '2019-05-21T09:59:43.000Z',
    description: 'Any application can be made scalable if designed properly. Agree? In our new article, we identify the most common scalability bottlenecks in the app architecture and tell how to avoid them at the engineering stage. Enjoy!',
    slug: 'how-to-build-a-scalable-web-application',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/045/original/main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 26,
    title: 'Trivia Game Development: How We Created a Trivia Mobile App for Studying the Bible',
    published_at: '2019-05-28T16:32:13.000Z',
    description: 'We created a cool trivia mobile game that allows people to study the Bible in an entertaining way. Quiz tours, daily challenges, daily gifts, lifelines, coins, bonus questions, leaderboard, amazing design… Get to know how we implemented such a great application!',
    slug: 'trivia-game-development-how-we-created-a-trivia-mobile-app-for-studying-the-bible',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/046/original/Biblemania_header.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 27,
    title: 'How to Create Your Own Trivia Game App?',
    published_at: '2019-06-04T19:48:41.000Z',
    description: 'The development of your own trivia game app can be funny and profitable! This article will give you the basic guide on how to create a trivia game app and make it stand out in the crowded marketplace. Keep reading!',
    slug: 'how-to-create-your-own-trivia-game-app',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/048/original/main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 28,
    title: 'Payment Gateway Integration in iOS and Android Apps',
    published_at: '2019-06-11T18:32:35.000Z',
    description: 'What is a payment gateway and how does it work? Why should you use it in your services? What payment gateway should you choose? How do you integrate it in your mobile application? Learn the answers!',
    slug: 'payment-gateway-integration-in-ios-and-android-apps',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/049/original/main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 29,
    title: 'How to Build a Trip Planner App for Organizing Travelling?',
    published_at: '2019-06-18T17:52:49.000Z',
    description: 'In our new article, we’re discussing how to utilize travel industry insights to create viable travel products, and share our experience of building one. ',
    slug: 'how-to-build-a-trip-planner-app-that-helps-organize-travelling',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/050/original/travel_new.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 30,
    title: "Choosing the Right Automation Testing Strategy: Do's and Don’ts",
    published_at: '2019-06-25T13:41:45.000Z',
    description: 'Choosing the right testing strategy might be truly challenging. Find out how to avoid risks, manage the development team, and save your time and money – all in this article!',
    slug: 'choosing-the-right-automation-testing-strategy-dos-and-don-ts',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/051/original/main.jpg',
    priority: priority.medium,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 31,
    title: 'How We Developed Telemojo, a Cloud-Based Contact Center Solution ',
    published_at: '2019-07-02T17:46:13.000Z',
    description: 'Meet our new project – Telemojo, an enterprise cloud-based contact center solution! Get to know how we built it using Twilio Flex, the first fully-programmable contact center platform for building contact centers faster and with ease! ',
    slug: 'how-we-developed-telemojo-a-cloud-based-contact-center-solution',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/052/original/main_new.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 32,
    title: 'How to Create a Cloud-Based Contact Center Platform?',
    published_at: '2019-07-09T20:26:48.000Z',
    description: 'The creation of a cloud-based contact center system will help you automate request processing, improve customer service, and increase customer loyalty. Find out how to build it!',
    slug: 'how-to-create-a-cloud-based-contact-center-platform',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/053/original/Contact_main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
  {
    id: 33,
    title: 'How Are Mobile Apps Transforming the Travel Industry?',
    published_at: '2019-07-16T18:59:17.000Z',
    description: 'Mobile apps are transforming the travel industry in an incredible way. Currently, mobile applications are competing with each other to make tourists’ experiences more personalized and sophisticated. In this article, we provide the best examples of how travel apps make your trips better.',
    slug: 'how-are-mobile-apps-transforming-the-travel-industry',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/054/original/van_header.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 34,
    title: 'How to Develop the Best Fitness App?',
    published_at: '2019-07-23T20:25:25.000Z',
    description: 'Since fitness apps continue to rule the world and conquer new markets, why not develop a fitness app worth millions of dollars? In fact, it is not that hard to create your own fitness application.',
    slug: 'how-to-develop-the-best-fitness-app',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/055/original/blog-01.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareChat.dynamicRouting,
    categoryName: tagsForBlog.softwareChat.name,
  },
  {
    id: 35,
    title: '6 Steps for Creating Your Own Personal Trainer App',
    published_at: '2019-07-30T19:48:10.000Z',
    description: 'As the fitness industry is booming currently, personal trainer software has become trendy. The development of fitness applications makes it much easier to do sports at any time around the globe. If you are dreaming about creating a personal trainer app, this article will provide you with plenty of insights!',
    slug: '6-steps-for-creating-your-own-personal-trainer-app',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/057/original/header.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 36,
    title: 'Best 6 Strategies for Monetizing Mobile Apps in 2019 and Beyond',
    published_at: '2019-08-06T20:52:43.000Z',
    description: 'Creating an amazing mobile app is great but how to make a profit and not disrupt customer loyalty? Take a look at the most popular mobile app monetization strategies and learn how to monetize yours!',
    slug: 'best-6-strategies-for-monetizing-mobile-apps-in-2019-and-beyond',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/058/original/main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 37,
    title: 'Twilio SIGNAL 2019 or How We Rocked San Francisco!',
    published_at: '2019-08-13T15:15:21.000Z',
    description: 'How the Yellow team visited Twilio SIGNAL 2019 in San Francisco, and why we enjoyed it so much!',
    slug: 'twilio-signal-2019-or-how-we-rocked-san-francisco',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/059/original/01.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 38,
    title: 'How to Create a Custom Hotel Management Software Program?',
    published_at: '2019-08-20T20:24:21.000Z',
    description: 'Want to run a hotel on your own? A quality property management software program will save you lots of time and money. In this article, we advise prospective hoteliers on how to bring new digital solutions to their business. Keep reading!',
    slug: 'how-to-create-a-custom-hotel-management-software',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/060/original/jungle_header.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 39,
    title: '7 Key Benefits of Continuous Delivery for Businesses',
    published_at: '2019-09-03T20:44:22.000Z',
    description: 'Is it possible to combine the production of quality software with fast releases? Yes! Think about Continuous Delivery – the ability to make safe and quick changes to software. In this article, we explain how it works and describe the benefits of continuous delivery for business.',
    slug: '7-key-benefits-of-continuous-delivery-for-businesses',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/061/original/ContinuousDelivery_main.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 40,
    title: 'Good RESTful API and How We Create It',
    published_at: '2019-09-17T12:17:46.000Z',
    description: 'Disclaimer: in this article, we decided not to dwell on the technical details of building a good API, as there are already really good articles on that (links included). Instead, we looked at the API from the usability perspective and compiled a checklist for you to ensure that your API is easy-to-use and secure.',
    slug: 'good-restful-api-and-how-we-make-it',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/062/original/header.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 41,
    title: 'How A/B Testing Helps to Improve Mobile App User Retention',
    published_at: '2019-10-01T12:16:20.000Z',
    description: 'Imagine that you have a seemingly great app, but for some strange reason it doesn’t bring enough customers. How to improve it wisely? In this article, we share our experience with A/B testing, which is a great instrument to make data-driven decisions on your product’s new features and maintain user retention.',
    slug: 'how-to-improve-in-app-user-retention-with-mobile-app-a-b-testing',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/063/original/main-2.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.softwareDevelopment.dynamicRouting,
    categoryName: tagsForBlog.softwareDevelopment.name,
  },
  {
    id: 42,
    title: 'Yellow is a Top B2B Company in Belarus',
    published_at: '2019-10-22T20:29:18.000Z',
    description: 'We are so happy to be officially featured as a leading company in Clutch’s 2019 report highlighting the top service providers in Eastern Europe! ',
    slug: 'yellow-is-a-top-b2b-company-in-belarus',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/066/original/Clutch-header.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 43,
    title: 'How to Create a Wireframe for Your Mobile App?',
    published_at: '2019-01-16T11:37:46.000Z',
    description: 'Figuring out what underlies a plain black-and-white wireframe—understanding the industry, users, budgeting and beyond.',
    slug: 'what-it-takes-to-create-a-wireframe',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/023/original/8.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 44,
    title: 'Why Create a Prototype, and How to Do It Right',
    published_at: '2019-11-12T20:47:20.000Z',
    description: 'Prototyping is the most crucial step in the whole software development process, and the most underappreciated one at the same time. Do you need it? Definitely! But why? Find the answers in the article! ',
    slug: 'why-create-a-prototype-and-how-to-do-it-right',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/069/original/main.png',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 45,
    title: 'How We Developed Drive Focus, the Perfect Training Tool for Enhancing Driving Skills',
    published_at: '2019-11-26T20:55:54.000Z',
    description: 'Meet Drive Focus – a tablet app for Android. It helps drivers rehabilitate after difficult medical conditions or life experiences that have affected their driving. The app will be of particular use for driving schools, universities, and medical research centers.',
    slug: 'how-we-developed-drive-focus-the-perfect-training-tool-for-enhancing-driving-skills',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/070/original/692*388.png',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
  {
    id: 46,
    title: 'Yellow Recognized on Clutch’s 1000 Top Developers',
    published_at: '2019-12-10T16:56:34.000Z',
    description: "And we're proud to be on the list!:)",
    slug: 'yellow-recognized-on-clutch-s-1000-top-developers',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/071/original/692x388.png',
    priority: priority.low,
    categoryTag: tagsForBlog.howWeWork.dynamicRouting,
    categoryName: tagsForBlog.howWeWork.name,
  },
  {
    id: 47,
    title: 'How We Developed A Super Blog for Tax Professionals ',
    published_at: '2019-12-24T15:21:19.000Z',
    description: 'It looks like big companies don’t want WordPress blogs anymore. Indeed, why bother with an outdated dashboard and messy plugins? What you really need is a tailor-made content solution with lots of cool features that are available when you want them. Keep reading to discover how we created a unique corporate blog for the NATP, America’s largest nonprofit organization for tax research and education! ',
    slug: 'how-we-developed-super-blog-for-tax-professionals',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/074/original/692-388_%281%29.png',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
  {
    id: 48,
    title: '7pm Thursday – A Dating App for the Next Generation',
    published_at: '2020-01-15T19:50:59.000Z',
    description: "How do you find true love? It’s a question everyone asks themselves at least once in their life. In the last century, everything was simple: if you liked a person, you just went to them and started communicating. As simple as that. But these days it doesn't work like that, so check out how we created a true dating app of the future.",
    slug: '7pm-thursday-a-dating-app-for-the-next-generation',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/075/original/header_preview-2.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 49,
    title: 'How a Voice Bot Can Take the Pain Out of Buying Insurance',
    published_at: '2020-02-11T14:52:11.000Z',
    description: 'These days, it’s hard to surprise someone with an artificial voice assistant. This kind of software is used in many areas of our life, from controlling smart devices to customer service. Recently, a client partnered with us to create a voice bot that works in the insurance industry.',
    slug: 'how-a-voice-bot-can-take-the-pain-out-of-buying-insurance',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/077/original/VoiceBot-header_preview.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
  {
    id: 50,
    title: 'How to Create a Voice Bot Without Google',
    published_at: '2020-02-18T16:59:23.000Z',
    description: 'Google is one of the most famous tech companies in the world. Their solutions are present in every area of our life, and software development is no exception. But what if something prevents us from using its tools? Take a look at our article about developing software without Google tools.',
    slug: 'how-to-create-a-voice-bot-without-google',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/078/original/388_692_%281%29.png',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
  {
    id: 51,
    title: 'Hotel Data Cloud – An Easy Way to Manage Information about Hotel Properties',
    published_at: '2020-02-25T15:52:50.000Z',
    description: 'Managing information about hotels and getting that information out to potential customers is a daunting process. Hotel properties come in many different types and each has a vast array of characteristics that must be taken into account and accurately represented on travel sites where potential guests book their travel plans. How to handle this? Use Hotel Data Cloud! ',
    slug: 'hotel-data-cloud-an-easy-way-to-manage-information-about-hotel-properties',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/079/original/hotel__preview.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 52,
    title: 'Why Your Startup Idea Is Not as Good as You Think',
    published_at: '2020-03-03T15:20:32.000Z',
    description: 'A lot of people think that a great idea is the one and only key to cashing in with a successful startup. The sad truth is that this kind of thinking is what frequently sinks a startup. A good idea is important, but definitely not the first priority. Check out our article and find out what makes a startup flourish.',
    slug: 'why-your-startup-idea-is-not-as-good-as-you-think',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/080/original/Startup_preview.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 53,
    title: 'SmartСenter – A Big Platform for Small Tax Firms',
    published_at: '2020-03-10T14:51:18.000Z',
    description: 'Meet SmartСenter – a special online platform that helps small tax firms organize their work. Combining a CRM system and a task manager, it keeps clients’ tax information in one place and tracks all the company’s activity. ',
    slug: 'smartcenter-a-big-platform-for-small-tax-firms',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/081/original/2small.jpg',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 54,
    title: 'Why You Need Research for Your Future Projects (with Examples) ',
    published_at: '2020-03-17T16:10:02.000Z',
    description: 'Sometimes people think research is only needed for the sciences. Yet these days, research in various forms and shapes is all around us, and software development is no exception. Check out this article and see why you should never underestimate the power of research in tech.',
    slug: 'why-you-need-research-for-your-future-projects-with-examples',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/082/original/692-388.png',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
  {
    id: 55,
    title: 'Dialog House – A New Way to Build the Chat App You Need',
    published_at: '2020-03-24T16:45:35.000Z',
    description: 'Using chats and chatbots for business needs is not a novelty these days. These solutions help companies build trusting relationships with their communities and facilitate customer service. But what should your business do if you need a chatbot but have no development team? Dialog House is a solid choice for building a custom chat solution. ',
    slug: 'dialog-house-a-new-way-to-build-the-chat-app-you-need',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/083/original/692-388_%281%29.png',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 56,
    title: 'An MVP Can Save Your Product’s Life',
    published_at: '2020-03-31T16:31:27.000Z',
    description: 'In this article, we will explain why your idea will never succeed without a minimum viable product (MVP). Seriously. This is no exaggeration.',
    slug: 'an-mvp-can-save-your-product-s-life',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/084/original/692-388_%281%29.png',
    priority: priority.low,
    categoryTag: tagsForBlog.marketing.dynamicRouting,
    categoryName: tagsForBlog.marketing.name,
  },
  {
    id: 57,
    title: 'UI/UX Design Is a Link in the Chain Between Art and Tech',
    published_at: '2020-04-07T17:01:04.000Z',
    description: 'UI/UX design is both easy and difficult at the same time. At this stage of the project, everyone knows what to do, and yet that process still has some peculiarities that must be taken into account. Check out our article and learn how to successfully combine art and technology.',
    slug: 'ui-ux-design-is-a-link-in-the-chain-between-art-and-tech',
    image: 'http://s3-eu-central-1.amazonaws.com/yellow.studio/posts/preview_images/000/000/085/original/388-692.png',
    priority: priority.low,
    categoryTag: tagsForBlog.yellow.dynamicRouting,
    categoryName: tagsForBlog.yellow.name,
  },
];
